### ISSUE TITLE
How did you extract meta data from apk file?

### ISSUE THREAD

**Issue by sohailmomin** [alexMyG/ADROIT#1]

**Comment by alexMyG** [comment]
We downloaded meta-information from the webpage of the app store that we used to download samples. We also employed information extracted from the Android Manifest. You can use apktool to decompile the .apk and extract the Manifest.
Take a look at our paper:
http://ieeexplore.ieee.org/abstract/document/7849904/

**Comment by sohailmomin** [comment]
Thanks
